/* This file is generated by scripts/generate-narration.mjs. */

export const NARRATION_GENERATION = {
  tool: "hyperframes tts",
  toolVersion: "0.7.64",
  engine: "Kokoro-82M",
  voice: "bf_emma",
  speed: 0.92,
  format: {
    channels: 1,
    sampleRate: 24000,
    bitsPerSample: 16,
  },
} as const;

export const NARRATION_CUE_IDS = [
  "tutorial-intro",
  "place-car",
  "baseline",
  "place-tower",
  "tower-fail",
  "regression",
  "targeted",
  "release",
  "school",
  "harbor",
  "storm",
  "finale",
] as const;

export type NarrationCueId = (typeof NARRATION_CUE_IDS)[number];

export interface NarrationCue {
  readonly id: NarrationCueId;
  readonly fileName: string;
  /** Relative to the deployed document, so Vite base paths and GitHub Pages work. */
  readonly src: string;
  readonly text: string;
  readonly durationSeconds: number;
  readonly bytes: number;
  readonly sha256: string;
}

export const NARRATION_MANIFEST = {
  "tutorial-intro": {
    id: "tutorial-intro",
    fileName: "tutorial-intro.wav",
    src: "audio/narration/tutorial-intro.wav",
    text: "Welcome to Kaiju QA. This little helper means well. Your job is to prove it is safe.",
    durationSeconds: 5.397,
    bytes: 259116,
    sha256: "b73a6c2f3f73f67b41b3514a127deb16e8253eee4e335c0b76a816fe794e6813",
  },
  "place-car": {
    id: "place-car",
    fileName: "place-car.wav",
    src: "audio/narration/place-car.wav",
    text: "Grab the stalled car and snap it into the glowing street.",
    durationSeconds: 3.051,
    bytes: 146476,
    sha256: "58e6b3f0835e956eba62aa47d29468c8480f5544eb6ede92454cc63992faad90",
  },
  "baseline": {
    id: "baseline",
    fileName: "baseline.wav",
    src: "audio/narration/baseline.wav",
    text: "Pull the test lever. One happy path is not permission to ship.",
    durationSeconds: 3.648,
    bytes: 175148,
    sha256: "59e81c4d5d44e6857e7fb20aed4088c2a820c3ad6aa001cb7a425028965328bb",
  },
  "place-tower": {
    id: "place-tower",
    fileName: "place-tower.wav",
    src: "audio/narration/place-tower.wav",
    text: "Place the fragile tower beside the route. Same behavior, tougher evidence.",
    durationSeconds: 4.693,
    bytes: 225324,
    sha256: "c2bcd525ad2d1b236c26b7b049be617dbfd88be84bd4482b8594268ec515e684",
  },
  "tower-fail": {
    id: "tower-fail",
    fileName: "tower-fail.wav",
    src: "audio/narration/tower-fail.wav",
    text: "The tower failed. Try the broad freeze rule, then rerun every test.",
    durationSeconds: 4.16,
    bytes: 199724,
    sha256: "b5b3a9d23088230cb7894e75eb3120ee894d5be51b27b238cc7ee2453c9a165e",
  },
  "regression": {
    id: "regression",
    fileName: "regression.wav",
    src: "audio/narration/regression.wav",
    text: "Tower safe. Ambulance blocked. The fix broke an old pass.",
    durationSeconds: 3.691,
    bytes: 177196,
    sha256: "c0be20eda8d9de35a4439ecb200ce685aa1f5b791668c59cb6c384444e82a369",
  },
  "targeted": {
    id: "targeted",
    fileName: "targeted.wav",
    src: "audio/narration/targeted.wav",
    text: "Swap in the striped slow zone. Change only where the hazard exists.",
    durationSeconds: 4.053,
    bytes: 194604,
    sha256: "310b1a0469ae16cf04fcdfa487db17c2a216699658d6f4750fed5411adfc066c",
  },
  "release": {
    id: "release",
    fileName: "release.wav",
    src: "audio/narration/release.wav",
    text: "Three passes, no regressions. Press the release stamp.",
    durationSeconds: 3.264,
    bytes: 156716,
    sha256: "108d4971da0e0f444c9472f618633f466923268815074ab6dc65b0775b99c6d4",
  },
  "school": {
    id: "school",
    fileName: "school.wav",
    src: "audio/narration/school.wav",
    text: "School crossing. Protect walkers without slowing the emergency route.",
    durationSeconds: 3.947,
    bytes: 189484,
    sha256: "be2aca2dfc86eae3bd7a8f4eb52959055a965c5fb0b684fe2f86dd5764f1cd8b",
  },
  "harbor": {
    id: "harbor",
    fileName: "harbor.wav",
    src: "audio/narration/harbor.wav",
    text: "Harbor load test. Check the heavy cargo boundary, not just the easy crate.",
    durationSeconds: 4.608,
    bytes: 221228,
    sha256: "52c5de51a367693a763a00d3a2e0daa0fd4fdec295bdfa35c144a715a253cc37",
  },
  "storm": {
    id: "storm",
    fileName: "storm.wav",
    src: "audio/narration/storm.wav",
    text: "Storm shift. Add the rain condition and preserve every rescue route.",
    durationSeconds: 3.904,
    bytes: 187436,
    sha256: "ef285bd9f457e60ef4170a827ef6e35f6b71fa52ecaeb018dcc2849ba4b94e9a",
  },
  "finale": {
    id: "finale",
    fileName: "finale.wav",
    src: "audio/narration/finale.wav",
    text: "Evidence accepted. Release earned. Our baby kaiju is ready for the city.",
    durationSeconds: 4.8,
    bytes: 230444,
    sha256: "1cb9fda4ee7aa7cbb89610bfa2d3ad9dae38d545c56d8fdfbcaffef5cb8ea30d",
  },
} as const satisfies Readonly<Record<NarrationCueId, NarrationCue>>;

export const NARRATION_TOTAL_DURATION_SECONDS = 49.216;

const NARRATION_CUE_ID_SET = new Set<string>(NARRATION_CUE_IDS);

export function isNarrationCueId(value: string): value is NarrationCueId {
  return NARRATION_CUE_ID_SET.has(value);
}

export function getNarrationCue(cueId: NarrationCueId): NarrationCue {
  return NARRATION_MANIFEST[cueId];
}
