/* This file is generated by scripts/generate-narration.mjs. */

export const NARRATION_GENERATION = {
  provider: "ElevenLabs",
  voiceId: "TZl0VZDEkMLBwlPLAKD9",
  modelId: "eleven_multilingual_v2",
  outputFormat: "mp3_44100_128",
} as const;

export const NARRATION_CUE_IDS = [
  "tutorial-intro",
  "place-car",
  "baseline",
  "place-tower",
  "tower-fail",
  "regression",
  "targeted",
  "release",
  "school",
  "harbor",
  "storm",
  "finale",
] as const;

export type NarrationCueId = (typeof NARRATION_CUE_IDS)[number];

export interface NarrationCue {
  readonly id: NarrationCueId;
  readonly fileName: string;
  /** Relative to the deployed document, so Vite base paths and GitHub Pages work. */
  readonly src: string;
  readonly text: string;
  readonly durationSeconds: number;
  readonly bytes: number;
  readonly sha256: string;
}

export const NARRATION_MANIFEST = {
  "tutorial-intro": {
    id: "tutorial-intro",
    fileName: "tutorial-intro.mp3",
    src: "audio/narration/tutorial-intro.mp3",
    text: "Welcome to Kaiju QA. This little helper means well. Your job is to prove it is safe.",
    durationSeconds: 5.303,
    bytes: 84889,
    sha256: "44576a7ac09a1199dc8c6dc9ca26d9e828bfa019bc2f0d7729301e387dfa6d8b",
  },
  "place-car": {
    id: "place-car",
    fileName: "place-car.mp3",
    src: "audio/narration/place-car.mp3",
    text: "Grab the stalled car and snap it into the glowing street.",
    durationSeconds: 3.396,
    bytes: 54378,
    sha256: "f7fb88bf01d6aca940349423282a4f1b25a4f092fbeb8cd73a075b5314eaaacb",
  },
  "baseline": {
    id: "baseline",
    fileName: "baseline.mp3",
    src: "audio/narration/baseline.mp3",
    text: "Pull the test lever. One happy path is not permission to ship.",
    durationSeconds: 3.814,
    bytes: 61066,
    sha256: "c185d9cc7f0ba6219685ecb6f637b67d65d51e72713f886d52d706c69dbf3d0e",
  },
  "place-tower": {
    id: "place-tower",
    fileName: "place-tower.mp3",
    src: "audio/narration/place-tower.mp3",
    text: "Place the fragile tower beside the route. Same behavior, tougher evidence.",
    durationSeconds: 4.989,
    bytes: 79874,
    sha256: "f42cbe856c1fea0e9941d66055734013a706f6b2b898616c5fa65339da9b4abf",
  },
  "tower-fail": {
    id: "tower-fail",
    fileName: "tower-fail.mp3",
    src: "audio/narration/tower-fail.mp3",
    text: "The tower failed. Try the broad freeze rule, then rerun every test.",
    durationSeconds: 4.284,
    bytes: 68589,
    sha256: "ff7278578f98e6a28c4c56b27f243daadebfbe52dfb9de4005cdfcc9dd34011d",
  },
  "regression": {
    id: "regression",
    fileName: "regression.mp3",
    src: "audio/narration/regression.mp3",
    text: "Tower safe. Ambulance blocked. The fix broke an old pass.",
    durationSeconds: 4.023,
    bytes: 64409,
    sha256: "e076aea60a640f2d28bae288344777c6417adefd373531aab6ec73d817b40437",
  },
  "targeted": {
    id: "targeted",
    fileName: "targeted.mp3",
    src: "audio/narration/targeted.mp3",
    text: "Swap in the striped slow zone. Change only where the hazard exists.",
    durationSeconds: 4.153,
    bytes: 66499,
    sha256: "96a140f847c29d640fe8a4ede5fbfb4278b99642fd41501cce346f6ba23d17bc",
  },
  "release": {
    id: "release",
    fileName: "release.mp3",
    src: "audio/narration/release.mp3",
    text: "Three passes, no regressions. Press the release stamp.",
    durationSeconds: 3.788,
    bytes: 60648,
    sha256: "e8e912c2124862f3211a297e3d317740bf8f5efefcab52a33af0e7f7ff4ad4ca",
  },
  "school": {
    id: "school",
    fileName: "school.mp3",
    src: "audio/narration/school.mp3",
    text: "School crossing. Protect walkers without slowing the emergency route.",
    durationSeconds: 4.389,
    bytes: 70261,
    sha256: "cd8af0409b90d9c44627c6d7c07614be550a0627cbff7eb9ec308ea9e840652a",
  },
  "harbor": {
    id: "harbor",
    fileName: "harbor.mp3",
    src: "audio/narration/harbor.mp3",
    text: "Harbor load test. Check the heavy cargo boundary, not just the easy crate.",
    durationSeconds: 4.702,
    bytes: 75276,
    sha256: "94f51b4a8b2dff021b3b8329d4f2d88fe6fc588d7d174f04c1e52be261df4138",
  },
  "storm": {
    id: "storm",
    fileName: "storm.mp3",
    src: "audio/narration/storm.mp3",
    text: "Storm shift. Add the rain condition and preserve every rescue route.",
    durationSeconds: 4.441,
    bytes: 71097,
    sha256: "166c2bbb42b03462ad2d73b70264b49dc29f2af793d6d8ecd874ee9175a3d4b0",
  },
  "finale": {
    id: "finale",
    fileName: "finale.mp3",
    src: "audio/narration/finale.mp3",
    text: "Evidence accepted. Release earned. Our baby kaiju is ready for the city.",
    durationSeconds: 5.068,
    bytes: 81128,
    sha256: "5465187d9df7f0ce79e2ca83f4113760b16a3c266a3f305bcf2c537f0fa7c7b3",
  },
} as const satisfies Readonly<Record<NarrationCueId, NarrationCue>>;

export const NARRATION_TOTAL_DURATION_SECONDS = 52.349;

const NARRATION_CUE_ID_SET = new Set<string>(NARRATION_CUE_IDS);

export function isNarrationCueId(value: string): value is NarrationCueId {
  return NARRATION_CUE_ID_SET.has(value);
}

export function getNarrationCue(cueId: NarrationCueId): NarrationCue {
  return NARRATION_MANIFEST[cueId];
}
