/* This file is generated by scripts/generate-narration.mjs. */

export const NARRATION_GENERATION = {
  provider: "ElevenLabs",
  voiceId: "wBXNqKUATyqu0RtYt25i",
  modelId: "eleven_multilingual_v2",
  outputFormat: "mp3_44100_128",
} as const;

export const NARRATION_CUE_IDS = [
  "tutorial-intro",
  "place-car",
  "baseline",
  "place-tower",
  "tower-fail",
  "regression",
  "targeted",
  "release",
  "school",
  "harbor",
  "storm",
  "finale",
] as const;

export type NarrationCueId = (typeof NARRATION_CUE_IDS)[number];

export interface NarrationCue {
  readonly id: NarrationCueId;
  readonly fileName: string;
  /** Relative to the deployed document, so Vite base paths and GitHub Pages work. */
  readonly src: string;
  readonly text: string;
  readonly durationSeconds: number;
  readonly bytes: number;
  readonly sha256: string;
}

export const NARRATION_MANIFEST = {
  "tutorial-intro": {
    id: "tutorial-intro",
    fileName: "tutorial-intro.mp3",
    src: "audio/narration/tutorial-intro.mp3",
    text: "Welcome to Kaiju QA. This little helper means well. Your job is to prove it is safe.",
    durationSeconds: 5.669,
    bytes: 91159,
    sha256: "90e8379eaeea16cc439f8ae3c1579a6b07ce9474a26faefaa3fb4137e488057c",
  },
  "place-car": {
    id: "place-car",
    fileName: "place-car.mp3",
    src: "audio/narration/place-car.mp3",
    text: "Grab the stalled car and snap it into the glowing street.",
    durationSeconds: 3.161,
    bytes: 51035,
    sha256: "61109b9fb64a2c6c16a5f2a4d6a93b46ee94e3c559a9ae0eaaec484972137927",
  },
  "baseline": {
    id: "baseline",
    fileName: "baseline.mp3",
    src: "audio/narration/baseline.mp3",
    text: "Pull the test lever. One happy path is not permission to ship.",
    durationSeconds: 3.84,
    bytes: 61902,
    sha256: "4e8fe1f2e53054ac2ed36bd3dd2ce8a987ce562258839f25430bdf4a6b9a07fb",
  },
  "place-tower": {
    id: "place-tower",
    fileName: "place-tower.mp3",
    src: "audio/narration/place-tower.mp3",
    text: "Place the fragile tower beside the route. Same behavior, tougher evidence.",
    durationSeconds: 4.362,
    bytes: 70261,
    sha256: "3eb8cdfe97314c632826c229d441c8aebf4c99636ccb8f186808ece19b8c2d3e",
  },
  "tower-fail": {
    id: "tower-fail",
    fileName: "tower-fail.mp3",
    src: "audio/narration/tower-fail.mp3",
    text: "The tower failed. Try the broad freeze rule, then rerun every test.",
    durationSeconds: 4.362,
    bytes: 70261,
    sha256: "b26f76bc8fd8535c6935bd232ce303d2daf3e54c75152013ff9ca21bcd72b123",
  },
  "regression": {
    id: "regression",
    fileName: "regression.mp3",
    src: "audio/narration/regression.mp3",
    text: "Tower safe. Ambulance blocked. The fix broke an old pass.",
    durationSeconds: 3.239,
    bytes: 52288,
    sha256: "4e40d63bd80790214a77320d246156e45d49b9cbc56f050d50167e886b45f390",
  },
  "targeted": {
    id: "targeted",
    fileName: "targeted.mp3",
    src: "audio/narration/targeted.mp3",
    text: "Swap in the striped slow zone. Change only where the hazard exists.",
    durationSeconds: 4.31,
    bytes: 69425,
    sha256: "772ee1b422683975e9c9f5b274cf33edb4b357a2044fca78a75cda1e79f1b8eb",
  },
  "release": {
    id: "release",
    fileName: "release.mp3",
    src: "audio/narration/release.mp3",
    text: "Three passes, no regressions. Press the release stamp.",
    durationSeconds: 3.344,
    bytes: 53960,
    sha256: "11d9e6db576c29d35332b37ea89082ba716df4190dafb00ce7ec4c5cfd5eb6b0",
  },
  "school": {
    id: "school",
    fileName: "school.mp3",
    src: "audio/narration/school.mp3",
    text: "School crossing. Protect walkers without slowing the emergency route.",
    durationSeconds: 4.441,
    bytes: 71515,
    sha256: "aa573e40783316097102afb07c75e794ff4f50a8eef72ec07ceef2e069da809a",
  },
  "harbor": {
    id: "harbor",
    fileName: "harbor.mp3",
    src: "audio/narration/harbor.mp3",
    text: "Harbor load test. Check the heavy cargo boundary, not just the easy crate.",
    durationSeconds: 4.127,
    bytes: 66499,
    sha256: "c326c8b0a36c474c4315d2c8d29b24285f4d16768edc11111fccc807622fc5fb",
  },
  "storm": {
    id: "storm",
    fileName: "storm.mp3",
    src: "audio/narration/storm.mp3",
    text: "Storm shift. Add the rain condition and preserve every rescue route.",
    durationSeconds: 4.127,
    bytes: 66499,
    sha256: "6d90cf1ed1542c8d5649f939ea3e9ac4d6acd717e74cec5796d6b1d91683dd21",
  },
  "finale": {
    id: "finale",
    fileName: "finale.mp3",
    src: "audio/narration/finale.mp3",
    text: "Evidence accepted. Release earned. Our baby kaiju is ready for the city.",
    durationSeconds: 4.493,
    bytes: 72351,
    sha256: "6e7de73d19d15f04fd9b4797d26612d97e6f63eec277480aa38ded45c04e460a",
  },
} as const satisfies Readonly<Record<NarrationCueId, NarrationCue>>;

export const NARRATION_TOTAL_DURATION_SECONDS = 49.476;

const NARRATION_CUE_ID_SET = new Set<string>(NARRATION_CUE_IDS);

export function isNarrationCueId(value: string): value is NarrationCueId {
  return NARRATION_CUE_ID_SET.has(value);
}

export function getNarrationCue(cueId: NarrationCueId): NarrationCue {
  return NARRATION_MANIFEST[cueId];
}
